# Generated by Django 5.2.6 on 2025-09-20 23:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conflicto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Conflicto')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Conflicto',
                'verbose_name_plural': 'Conflictos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='FuerzaArmada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Oficial')),
                ('rama', models.CharField(choices=[('EJE', 'Ejército'), ('ARM', 'Armada'), ('FAE', 'Fuerza Aérea'), ('MAR', 'Infantería de Marina'), ('OTR', 'Otra')], max_length=3)),
            ],
            options={
                'verbose_name': 'Fuerza Armada',
                'verbose_name_plural': 'Fuerzas Armadas',
                'ordering': ['pais__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del País')),
                ('bandera', models.ImageField(blank=True, null=True, upload_to='banderas/', verbose_name='Bandera')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('funcionamiento', models.TextField(help_text='Descripción técnica de cómo opera el arma.')),
                ('mecanismos', models.TextField(help_text='Detalles sobre los mecanismos internos (ej. cerrojo rotativo, retroceso de masas).')),
                ('conflictos_uso', models.ManyToManyField(blank=True, related_name='armas_utilizadas', to='armament.conflicto', verbose_name='Conflictos en donde se utilizó')),
                ('operadores', models.ManyToManyField(blank=True, related_name='arsenal', to='armament.fuerzaarmada', verbose_name='Fuerzas Armadas que la utilizan')),
                ('pais_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='armas_disenadas', to='armament.pais')),
            ],
            options={
                'verbose_name': 'Arma',
                'verbose_name_plural': 'Armas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='fuerzaarmada',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuerzas_armadas', to='armament.pais'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('CAZ', 'Avión de Caza'), ('BOM', 'Bombardero'), ('HEL', 'Helicóptero de Ataque'), ('TRA', 'Avión de Transporte'), ('TAN', 'Tanque')], max_length=3)),
                ('conflictos_uso', models.ManyToManyField(blank=True, related_name='vehiculos_utilizados', to='armament.conflicto')),
                ('operadores', models.ManyToManyField(blank=True, related_name='inventario_vehiculos', to='armament.fuerzaarmada')),
                ('pais_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_disenados', to='armament.pais')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecursoMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('SD', 'Sonido de Disparo'), ('SR', 'Sonido de Recarga'), ('A3D', 'Animación 3D'), ('IMG', 'Imagen de Galería')], max_length=3)),
                ('archivo', models.FileField(upload_to='recursos_multimedia/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'mp4', 'webm', 'jpg', 'png'])])),
                ('arma_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='armament.arma')),
                ('vehiculo_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='armament.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Derribo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(help_text='Detalles y relato del derribo.')),
                ('arma_victoriosa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derribos_logrados', to='armament.arma')),
                ('conflicto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derribos', to='armament.conflicto')),
                ('vehiculo_derribado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derribos_sufridos', to='armament.vehiculo')),
                ('vehiculo_victorioso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derribos_logrados', to='armament.vehiculo')),
            ],
            options={
                'verbose_name': 'Derribo',
                'verbose_name_plural': 'Derribos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='fuerzaarmada',
            unique_together={('pais', 'nombre')},
        ),
    ]
