# Generated by Django 5.2.6 on 2025-09-21 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='tipo',
            field=models.CharField(choices=[('RA', 'Rifle de Asalto'), ('PI', 'Pistola'), ('FR', 'Rifle de Francotirador'), ('ES', 'Escopeta'), ('SF', 'Subfusil'), ('OT', 'Otro')], default='OT', help_text='El tipo de arma (ej. Rifle de Asalto).', max_length=2),
        ),
        migrations.AlterField(
            model_name='recursomultimedia',
            name='archivo',
            field=models.FileField(upload_to='recursos_multimedia/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'mp4', 'webm', 'jpg', 'png', 'glb'])]),
        ),
    ]
