# Generated by Django 5.2.6 on 2026-02-21 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armament', '0002_arma_tipo_alter_recursomultimedia_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoArmamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AA', 'Aire-Aire'), ('AT', 'Aire-Tierra'), ('AR', 'Antiradar'), ('CA', 'Cañón'), ('OT', 'Otro')], max_length=2)),
                ('nombre', models.CharField(max_length=150)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armamento', to='armament.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='armament.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoFichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_vuelo', models.DateField(blank=True, null=True)),
                ('entrada_servicio', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('longitud', models.CharField(blank=True, max_length=50)),
                ('altura', models.CharField(blank=True, max_length=50)),
                ('envergadura', models.CharField(blank=True, max_length=50)),
                ('superficie_alar', models.CharField(blank=True, max_length=50)),
                ('peso_vacio', models.CharField(blank=True, max_length=50)),
                ('peso_maximo', models.CharField(blank=True, max_length=50)),
                ('velocidad_maxima', models.CharField(blank=True, max_length=50)),
                ('alcance', models.CharField(blank=True, max_length=50)),
                ('techo_servicio', models.CharField(blank=True, max_length=50)),
                ('motor', models.CharField(blank=True, max_length=150)),
                ('tripulacion', models.CharField(blank=True, max_length=100)),
                ('costo_unitario', models.CharField(blank=True, max_length=100)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='armament.vehiculo')),
            ],
        ),
    ]
