# Generated by Django 5.2.6 on 2026-02-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armament', '0003_vehiculoarmamento_vehiculocaracteristica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuerzaarmada',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo o insignia de la fuerza armada', null=True, upload_to='logos_fuerzas_armadas/', verbose_name='Logo/Insignia'),
        ),
    ]
